apiVersion: v1
kind: Pod
metadata:
  name: nginx-local
  namespace: pfa
spec:
  containers:
  - name: nginx
    image: docker.io/library/nginx:latest
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 80

